### ISSUE TITLE
[Maintenance]: Update workflows to run on newer node version

### ISSUE THREAD

**Issue by LukeyBit** [LukeyBit/Project-CV#51]
### Contact Details

@LukeyBit

### Area

CD/CI

### What is the feature?

Update the workflows to use a newer version of Node:

```yaml
- uses: actions/setup-node@v2
  with:
     node-version: 18
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
